src/main/java/com/JAZ/zadanie_4/domain/Patient.java
package com.JAZ.zadanie_4.domain;

import java.util.Date;

public class Patient {

    String dateAdded;
    String name;
    String surname;
    String pesel;
    Date birthDate;
    String address;
    String phoneNumber;
    String weight;
    String height; 
    
    public String getDateAdded() {
        return dateAdded;
    }

    public void setDateAdded(String dateAdded) {
        this.dateAdded = dateAdded;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getPesel() {
        return pesel;
    }

    public void setPesel(String pesel) {
        this.pesel = pesel;
    }

    public Date getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getHeight() {
        return height;
    }

    public void setHeight(String height) {
        this.height = height;
    }  
    
}

src/main/java/com/JAZ/zadanie_4/web/PatientBean.java
package com.JAZ.zadanie_4.web;

import com.JAZ.zadanie_4.domain.Patient;
import com.JAZ.zadanie_4.service.PatientRepository;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.component.UIForm;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;
import javax.faces.event.ComponentSystemEvent;
import javax.faces.event.ValueChangeEvent;
import javax.faces.validator.ValidatorException;
import javax.inject.Named;
import javax.inject.Inject;

@SessionScoped
@Named("patientBean")
public class PatientBean implements Serializable {  
        
    private Patient patient = new Patient();
        
    private List<Patient> filteredData;  

    public PatientBean() {
        this.db = new PatientRepository();
    }
        
    public Patient getPatient() {
        return patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }
    
    public List<Patient> getPatientData(){        
        return db.getList();
    }

    public List<Patient> getFilteredData() {
        return filteredData;
    }

    public void setFilteredData(List<Patient> filteredData) {
        this.filteredData = filteredData;
    }
    
    @Inject
    PatientRepository db;   
    
    public String addNewPatient(){
        db.addPatientToList(patient);              
        return "registeredPatient";
    }
    
    int weightFrom;
    int weightTo;    

    public int getWeightFrom() {
        return weightFrom;
    }
    
    public void setWeightFrom(ValueChangeEvent event) {
        String tempWeight = (String) event.getNewValue();        
        this.weightFrom = Integer.parseInt(tempWeight);
        
        System.out.println(weightFrom);
    }

    public int getWeightTo() {
        return weightTo;
    }

    public void setWeightTo(ValueChangeEvent event) {
        String tempWeight = (String) event.getNewValue();        
        this.weightTo = Integer.parseInt(tempWeight);
        
        System.out.println(weightTo);
    } 
    
    public void uniquePesel(FacesContext context, UIComponent component, Object value) {       
        String pesel = (String)value;
        
        for (Patient newPatient : db.getList()) {           
            if (newPatient.getPesel().equalsIgnoreCase(pesel)) {
		throw new ValidatorException(new FacesMessage(FacesMessage.SEVERITY_ERROR, 
                    "Nie można dublować numerów PESEL.", null));
            }
        }        
    }
    
    public void dateValidator(FacesContext context, UIComponent component, Object value) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/YYYY");
        
        Date date = (Date)value;        
        Date today = new Date();
        
        if (date.after(today) || dateFormat.format(date).equals(dateFormat.format(today))){
            throw new ValidatorException(new FacesMessage(FacesMessage.SEVERITY_ERROR, 
                "Podaj właściwą datę urodzenia.", null));
        }        
    }
    
    public void compareBirthdatePesel(ComponentSystemEvent event) {
        try {        
            UIForm form = (UIForm) event.getComponent();
            UIInput UIbirthDate = (UIInput) form.findComponent("birthdate");
            UIInput UIpesel = (UIInput) form.findComponent("pesel");

            String birthdate = UIbirthDate.getValue().toString().substring(27, 29);
            String pesel = UIpesel.getValue().toString().substring(0, 2);

            if (!birthdate.equals(pesel)) {
                FacesContext context = FacesContext.getCurrentInstance();
                context.addMessage(form.getClientId(), new FacesMessage(FacesMessage.SEVERITY_ERROR, 
                    "Data urodzenia jest niezgodna z numerem PESEL.", null));
                context.renderResponse();         
            }
        }
        catch (NullPointerException exception) {
        }
    }
}

src/main/webapp/addPatient.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
        xmlns:p="http://primefaces.org/ui" 
	template="/templates/default.xhtml">
	<ui:define name="content">
            <h:form id="patientForm">
                
                <f:event type="postValidate" listener="#{patientBean.compareBirthdatePesel}" />
                
                <h:panelGrid columns="3" cellpadding="10">
                    <p:outputLabel value="#{msg.patientName}" />
                    <p:inputText id="name" value="#{patientBean.patient.name}" 
                                    required="true" requiredMessage="#{err.fieldRequired}" 
                                        validatorMessage="#{err.rangeRequired}">
                        <f:validateLength minimum="2" maximum="50" />
                        <p:ajax update="msgName" event="keyup" />
                    </p:inputText>
                    <p:message for="name" id="msgName" />            
                    
                    <p:outputLabel value="#{msg.patientSurname}" />
                    <p:inputText id="surname" value="#{patientBean.patient.surname}" 
                                    required="true" requiredMessage="#{err.fieldRequired}" 
                                        validatorMessage="#{err.rangeRequired}">
                        <f:validateLength minimum="2" maximum="50" />
                        <p:ajax update="msgSurname" event="keyup" />
                    </p:inputText>                    
                    <p:message for="surname" id="msgSurname" /> 
                    
                    <p:outputLabel value="#{msg.patientPesel}" />                    
                    <p:inputMask mask="99999999999" id="pesel" value="#{patientBean.patient.pesel}" 
                                    validator="#{patientBean.uniquePesel}" required="true" 
                                        requiredMessage="#{err.fieldRequired}">
                        <p:ajax update="msgPesel" event="keyup" />
                        <f:validator validatorId="peselValidator" />
                    </p:inputMask>    
                    <p:message for="pesel" id="msgPesel" /> 
                    
                    <p:outputLabel value="#{msg.patientBirthdate}" />
                    <p:calendar id="birthdate" value="#{patientBean.patient.birthDate}"
                                    validator="#{patientBean.dateValidator}" required="true" 
                                        requiredMessage="#{err.fieldRequired}">                                   
                        <p:ajax update="msgBirthdate" event="dateSelect" />
                    </p:calendar>                    
                    <p:message for="birthdate" id="msgBirthdate" /> 
                    
                    <p:outputLabel value="#{msg.patientAddress}" />
                    <p:inputTextarea rows="2" cols="25" id="address" value="#{patientBean.patient.address}" 
                                        required="true" requiredMessage="#{err.fieldRequired}">
                        <p:ajax update="msgAddress" event="keyup" />
                    </p:inputTextarea>
                    <p:message for="address" id="msgAddress" /> 
                    
                    <p:outputLabel value="#{msg.patientPhoneNumber}" />
                    <p:inputMask mask="999-999-999" id="phoneNumber" value="#{patientBean.patient.phoneNumber}" />
                    <p:message for="phoneNumber" /> 
                    
                    <p:outputLabel value="#{msg.patientWeight}" />
                    <p:inputText id="weight" value="#{patientBean.patient.weight}" />
                    <p:message for="weight" /> 
                    
                     <p:outputLabel value="#{msg.patientHeight}" />
                     <p:inputText id="height" value="#{patientBean.patient.height}" />
                     <p:message for="height" /> 
                    
                    <p:commandButton value="#{msg.formReset}" type="reset" />
                    <p:commandButton value="#{msg.formSubmit}" type="submit" action="#{patientBean.addNewPatient()}" 
                                        validateClient="true" ajax="false" />
                </h:panelGrid>              
                        
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/home.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
        template="/templates/default.xhtml" >
</ui:composition>

src/main/webapp/index.jsp
<% response.sendRedirect("home.jsf"); %>

src/main/webapp/main/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
        xmlns:p="http://primefaces.org/ui">
    <div>
    <h:form>  
        <p:growl id="messages"/>

        <p:menubar>
            <p:menuitem value="#{msg.patientSearch}" url="/searchPatient.jsf" icon="ui-icon-search" />
            <p:menuitem value="#{msg.patientAdd}" url="/addPatient.jsf" icon="ui-icon-plus" />
            <p:menuitem value="#{msg.patientRegistered}" url="/registeredPatient.jsf" icon="ui-icon-person" />

            <f:facet name="options">
                <p:commandButton type="button" value="#{msg.tools}" icon="ui-icon-wrench" disabled="true" />
            </f:facet>
        </p:menubar>
    </h:form>
    </div>
</ui:composition>

src/main/webapp/registeredPatient.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
        xmlns:p="http://primefaces.org/ui" 
	template="/templates/default.xhtml">
	<ui:define name="content">
            <p:dataTable var="patient" value="#{patientBean.patientData}" emptyMessage="#{msg.patientListEmpty}">
                 <p:column headerText="#{msg.patientDateAdded}">
                    <h:outputText value="#{patient.dateAdded}" />
                </p:column>
                
                <p:column headerText="#{msg.patientName}">
                    <h:outputText value="#{patient.name}" />
                </p:column>

                <p:column headerText="#{msg.patientSurname}">
                    <h:outputText value="#{patient.surname}" />
                </p:column>
                
                <p:column headerText="#{msg.patientPesel}">
                    <h:outputText value="#{patient.pesel}" />
                </p:column>
                
                <p:column headerText="#{msg.patientWeight}">
                    <h:outputText value="#{patient.weight}" />
                </p:column>
                
                <p:column headerText="#{msg.patientHeight}">
                    <h:outputText value="#{patient.height}" />
                </p:column> 
            </p:dataTable>
	</ui:define>
</ui:composition>

src/main/webapp/searchPatient.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
        xmlns:p="http://primefaces.org/ui" 
	template="/templates/default.xhtml">
	<ui:define name="content">
            <h:form id="patientFilter">
                <p:dataTable var="patient" value="#{patientBean.patientData}" widgetVar="patientFilter"
                                emptyMessage="#{msg.patientNotFound}" filteredValue="#{patientBean.filteredData}">
                    
                    <p:column sortBy="#{patient.name}" filterBy="#{patient.name}" 
                              headerText="#{msg.patientName}" filterMatchMode="contains">
                        <h:outputText value="#{patient.name}" />
                    </p:column>

                    <p:column sortBy="#{patient.surname}" filterBy="#{patient.surname}" 
                              headerText="#{msg.patientSurname}" filterMatchMode="contains">
                        <h:outputText value="#{patient.surname}" />
                    </p:column>

                    <p:column sortBy="#{patient.pesel}" filterBy="#{patient.pesel}" 
                              headerText="#{msg.patientPesel}" filterMatchMode="contains">
                        <h:outputText value="#{patient.pesel}" />
                    </p:column> 
                
                </p:dataTable>
            </h:form>           
	</ui:define>
</ui:composition>

src/main/webapp/slider.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
        xmlns:p="http://primefaces.org/ui" 
	template="/templates/default.xhtml">
	<ui:define name="content">
            <h:form id="patientFilter">
                <p:dataTable var="patient" value="#{patientBean.patientData}" widgetVar="patientFilter"
                                emptyMessage="#{msg.patientNotFound}" filteredValue="#{patientBean.filteredData}">
                                                        
                    <p:column sortBy="#{patient.weight}" filterBy="#{patient.weight}"
                                headerText="#{msg.patientWeight}">                         
                        <f:facet name="filter" >                            
                            <h:outputText id="sliderValue" />
                            <p:slider for="weightFrom, weightTo" range="true" maxValue="200" 
                                        display="sliderValue" displayTemplate="#{msg.from} {min} #{msg.to} {max}">
                                <p:ajax event="slideEnd" process="weightFrom, weightTo" />
                            </p:slider>            
                            <h:inputHidden id="weightFrom" valueChangeListener="#{patientBean.setWeightFrom}" />
                            <h:inputHidden id="weightTo" valueChangeListener="#{patientBean.setWeightFrom}" />
                        </f:facet>                        
                        <h:outputText value="#{patient.weight}" />
                    </p:column>
                
                </p:dataTable>
            </h:form>           
	</ui:define>
</ui:composition>

src/main/webapp/templates/default.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
        xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>
        <ui:insert name="Welcome"></ui:insert>
    </title>
    <h:outputStylesheet name="style.css" />
</h:head>
<h:body>    
    <div class="header">
        <div class="headerImage">
            <h:graphicImage value="http://metsfanclub.com/wp-content/uploads/2013/08/mlb_logo_syringe1.png" height="150" />            
        </div>
        <div class="headerCompanyName">
            #{msg.headerCompanyName}
        </div>
    </div>
    <div class="menu">
        <ui:include src="/main/menu.xhtml" />
    </div>
    <div class="content">
        <div class="contentInternal">
            <ui:insert name="content" />
        </div>        
    </div>
</h:body>
</html>    